source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'TT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TT
  #pod 'PandaRepoSwift', :path => '../PandaRepoSwift'
  pod 'HandyJSON'
  pod 'Tiercel', '2.3.0'

  target 'TTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
