# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JJMoya' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JJMoya
pod 'Alamofire', '~> 5.0.0'

  target 'JJMoyaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JJMoyaUITests' do
    # Pods for testing
  end

end
